name: CI

on:

  push:


jobs:
  build:
    name: run unit tests
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: run jasimine through npm
        run: npm test
